name: Build Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"
          cache: 'gradle'
          
          
      - name: set permissions
        run: chmod +x gradlew

      - name: Build debug APK 
        run: ./gradlew assembleRelease
        
      - name: Upload unsigned apk 
        run: curl --upload-file app/build/outputs/apk/*/*/*.apk https://bashupload.com/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/*/*/*.apk
